<?php

namespace Sugarcrm\Tidbit\Generator;

/**
 * Interface DatabaseInterface
 * @package Sugarcrm\Tidbit\Generator
 */
interface DatabaseInterface
{
    /**
     * Clean up db table
     * Removes all the demo data and data generated by Tidbit
     *
     * @return mixed
     */
    public function clearDB();

    /**
     * Obliterate db table
     * Remove all data from the tables of DB affected by generator.
     *
     * @return mixed
     */
    public function obliterateDB();

    /**
     * Populate buffer method for Generators
     *
     * @return mixed
     */
    public function generate();
}
